services:
  db:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=${DATABASES_NAME}
      - POSTGRES_USER=${DATABASES_USER}
      - POSTGRES_PASSWORD=${DATABASES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRESQL_SHARED_BUFFERS=256MB
      - POSTGRESQL_EFFECTIVE_CACHE_SIZE=1GB
      - POSTGRESQL_WORK_MEM=16MB
      - POSTGRESQL_MAINTENANCE_WORK_MEM=128MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # - '127.0.0.1:5432:5432' # Только локальный доступ
      - '5432:5432' # Доступ открыт в сеть
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASES_USER} -d ${DATABASES_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:7.0.1
#    Данные сохраняются в файл и восстанавливаются после перезапуска
#    command: redis-server --appendonly yes
    command: redis-server  # Данные ТОЛЬКО в памяти, теряются при перезапуске
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  migrate:
    build: .
    command: >
      bash -c "echo 'Ожидаем запуск PostgreSQL 20с... Waiting for PostgreSQL...' &&
               sleep 20 &&
               python manage.py migrate"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - app_network

  createsuperuser:
    build: .
    env_file:
      - .env
    command: >
      bash -c "python manage.py createsu"
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: "no"
    networks:
      - app_network

  celery-beat-setup:
    build: .
    env_file:
      - .env
    command: python manage.py setup_celery_schedules
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: "no"
    profiles: ["setup"]
    networks:
      - app_network

  app:
    build: .
    env_file:
      - .env
    tty: true
    command: >
      bash -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=3"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - app_logs:/app/logs
    ports:
      - '8000:8000'
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy
      migrate:  # Ждем завершения миграций
        condition: service_completed_successfully
      createsuperuser: # добавляем зависимость от createsuperuser
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  celery:
    build: .
    env_file:
      - .env
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
      - celery_logs:/app/logs
    user: "1000:1000"
    depends_on:
      migrate:
        condition: service_completed_successfully  # Добавьте эту строку
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "celery", "-A", "config", "inspect", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  celery-beat:
    build: .
    env_file:
      - .env
    command: >
      bash -c "celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
      - celery_beat_logs:/app/logs
    user: "1000:1000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  flower:
    image: mher/flower:0.9.7
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_BASIC_AUTH=${FLOWER_USER}:${FLOWER_PASSWORD}
    volumes:
      - flower_data:/app/var
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5555/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/acme-challenge:/var/www/certbot
    command: renew --quiet --no-self-upgrade
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf:ro  # Для дополнительных SSL-настроек
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем директорию с сертификатами
      - /tmp/acme-challenge:/tmp/acme-challenge  # Для прохождения проверки Certbot
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app_network  # Рекомендуется использовать явно объявленную сеть

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  app_logs:
  celery_logs:
  celery_beat_logs:
  flower_data:

networks:
  app_network:
    driver: bridge
    name: webhook_app_network