services:
  db:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=${DATABASES_NAME}
      - POSTGRES_USER=${DATABASES_USER}
      - POSTGRES_PASSWORD=${DATABASES_PASSWORD}
      - DATABASES_NAME=${DATABASES_NAME}
      - DATABASES_USER=${DATABASES_USER}
      - DATABASES_PASSWORD=${DATABASES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRESQL_SHARED_BUFFERS=256MB
      - POSTGRESQL_EFFECTIVE_CACHE_SIZE=1GB
      - POSTGRESQL_WORK_MEM=16MB
      - POSTGRESQL_MAINTENANCE_WORK_MEM=128MB
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    ports:
      # - '127.0.0.1:5432:5432' # Только локальный доступ
      - '5432:5432' # Доступ открыт в сеть
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${DATABASES_PASSWORD} pg_isready -U ${DATABASES_USER} -d ${DATABASES_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:7.0.1
    # Данные сохраняются в файл и восстанавливаются после перезапуска
    # command: redis-server --appendonly yes
    # # Данные ТОЛЬКО в памяти, теряются при перезапуске
    command: redis-server
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  migrate:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: >
      bash -c "echo 'Ожидаем запуск PostgreSQL 20с... Waiting for PostgreSQL...' &&
               sleep 20 &&
               python manage.py migrate"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - app_network

  createsuperuser:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: >
      bash -c "python manage.py createsu"
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: "no"
    networks:
      - app_network

  celery-beat-setup:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: python manage.py setup_celery_schedules
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: "no"
    profiles: ["setup"]
    networks:
      - app_network

  app:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    tty: true
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers=3
      --timeout 120
      --max-requests 1000
      --max-requests-jitter 100
      --access-logfile -
    volumes:
      - /var/log/webhook_app/app:/app/logs  # логи на хосте
      - /opt/webhook_app/static:/app/static  # статика на хосте
      - /opt/webhook_app/media:/app/media    # медиа на хосте
    ports:
      - '8000:8000'
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy
      migrate:  # Ждем завершения миграций
        condition: service_completed_successfully
      createsuperuser: # добавляем зависимость от createsuperuser
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  celery:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
      - /var/log/webhook_app/celery:/app/logs  # логи на хосте
    user: "1000:1000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "celery", "-A", "config", "inspect", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  celery-beat:
    build: .
    env_file:
      - .env
    command: >
      bash -c "celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
      - /var/log/webhook_app/celery_beat:/app/logs  # логи на хосте
    user: "1000:1000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  flower:
    image: mher/flower:0.9.7
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_BASIC_AUTH=${FLOWER_USER}:${FLOWER_PASSWORD}
    volumes:
      - flower_data:/app/var
    # Убираем проброс порта, так как теперь используем через nginx
    #ports:
    #  - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://flower:5555/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    # не пробрасываем наружу, чтобы nginx мог подключиться к Flower:
    expose:
      - "5555"
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/acme-challenge:/var/www/certbot
    command: renew --quiet
    restart: "no"
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf:ro  # Для дополнительных SSL-настроек
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем директорию с сертификатами
      - /tmp/acme-challenge:/tmp/acme-challenge  # Для прохождения проверки Certbot
      - /opt/webhook_app/static:/app/static:ro
      - /opt/webhook_app/media:/app/media:ro
      - /var/log/webhook_app/nginx:/var/log/nginx
    depends_on:
      - app
      - flower
    restart: unless-stopped
    networks:
      - app_network  # Рекомендуется использовать явно объявленную сеть

volumes:
  postgres_prod_data:
    external: true
  redis_data:
  flower_data:

networks:
  app_network:
    driver: bridge
    name: webhook_app_network
    ipam:
      driver: default
      config:
        - subnet: "10.20.0.0/16"
          gateway: "10.20.0.1"